laravel-frontend-presets/tall

README.md
src/TallPreset.php
stubs/default/tailwind.config.js
stubs/default/webpack.mix.js

I don't know if this is something that anyone wants to do because it is incredibly opinionated, but I thought I would PR it anyway.
Tailwind v1.4 has PurgeCSS built-in now, so it's not strictly necessary we use Spatie's package. However, I know Tailwind's implementation does not automatically set up all the directories to scan.
This package will put the burden on the end developer to manage their own directories, but I can foresee an increase in tickets here because "CSS classes are missing".
If there are no objections, I will mark the PR as ready for review so it can be merged. Otherwise, we can close this PR.

Use Tailwind's built-in `purge`

---

src/TallPreset.php
stubs/default/resources/sass/app.scss
stubs/default/webpack.mix.js

This swaps out the default style compilation to use Sass instead of PostCSS. SCSS is the default that Laravel comes with out-of-the-box, so it's what a lot of people are familiar with and can get rolling with, especially if they don't use TailwindCSS exclusively. You still get PostCSS processing the Tailwind directives, so you don't really lose anything from it.

Use Sass compilation by default

---

stubs/default/resources/sass/app.scss

Fixes #7 
For some reason, in Firefox only, when opening a page that has an input including `wire:model`, Firefox is treating the input as invalid by default, and putting a red border around it, even if the user has not interacted with it at this point.
This small addition of CSS covers this scenario so inputs don't look broken on page load.

Add default styling to handle invalid input red borders in Firefox

---

src/TallPreset.php

This merge request updates the preset command to replace the usage of `RouteServiceProvider::HOME` within the `RedirectIfAuthenticated` middleware to use `route('home')` instead. This makes a default Laravel app completely used name routes instead of relying on a constant in only one place.

Update the preset to replace the only other usage of RouteServiceProvider::HOME

---

stubs/auth/resources/views/livewire/auth/login.blade.php
stubs/auth/resources/views/livewire/auth/passwords/confirm.blade.php
stubs/auth/resources/views/livewire/auth/passwords/email.blade.php
stubs/auth/resources/views/livewire/auth/passwords/reset.blade.php
stubs/auth/resources/views/livewire/auth/register.blade.php
stubs/auth/resources/views/livewire/auth/verify.blade.php
stubs/default/resources/views/welcome.blade.php

I think we need to add link to `route('home')` to the logo. Specially when visiting the login & register page. Users can't go back to the home page.
I can also add it to the logo component but I don't think the link belongs there since the content is only SVG.
Let me know what you think.

Add home link to logo

---

stubs/auth/resources/views/livewire/auth/login.blade.php
stubs/auth/resources/views/livewire/auth/passwords/email.blade.php
stubs/auth/resources/views/livewire/auth/passwords/reset.blade.php
stubs/auth/resources/views/livewire/auth/register.blade.php

The ID attribute is unnecessary for the error text.
Keeping only required elements in HTML will make it easy to read, clean, low on size.

Remove unnecessary ids from markup

---

stubs/auth/tests/Feature/Auth/RegisterTest.php

Currently test for a required name doesn't check the correct field, corrected to check for an error in the name property rather than email.

Update test for required field 'name'

---

stubs/auth/app/Http/Livewire/Auth/Register.php

Alternative to #26
Instead of firing `$user->sendEmailVerificationNotification();` directly, or checking if it has to be done manually; we can instead let this be handled by existing code from the framework itself. Triggering the `Registered` -event.
This way it also stays relevant to the documentation regarding Verification: https://laravel.com/docs/7.x/verification

Trigger the Registered event

---

src/TallPreset.php
stubs/default/tailwind.config.js

According with [Documentation of Tailwind UI](https://tailwindui.com/documentation#how-tailwindcss-ui-extends-tailwind) the `@tailwindcss/ui` includes the `@tailwindcss/custom-forms` plugin out of the box.
Is OK remove from our preset.

Remove Tailwind custom forms

---

stubs/auth/app/Http/Livewire/Auth/Login.php
stubs/auth/app/Http/Livewire/Auth/Register.php

If a user gets redirected to log in or register from a middleware, redirect them to their originally intended route once they've finished.

Redirect to the intended route upon login and registration

---

stubs/auth/tests/Feature/Auth/RegisterTest.php

This PR tests to make sure the `Registered` event is triggered when a user is registered.

Added Registered event check

---

stubs/default/resources/views/vendor/livewire/pagination-links.blade.php

There was a bug where the **"of"** word is not showing up after reaching last record of pagination then going back a page or to other numbered page.
Steps to recreate:
- Go to last page of pagination
- Go back to other pages or click **<**

Fix for pagination "of" results disappearing bug when navigating from last page.

---

src/TallPreset.php

This also resolves the version of the typography plugin which was incorrect (as it is still in 0.x, so should have been `0.1.4` rather than `1.4`).
Tailwind 1.5 doesn't support Typography 0.1.x, so this has also been updated to the latest version.
I've also bumped Tailwind UI to v0.4 which released yesterday.

chore: update to Tailwind 1.5

---

.github/workflows/phpunit.xml.stub
.github/workflows/tests.yml
README.md
composer.json
src/TallPreset.php
stubs/auth/app/Http/Livewire/Auth/Login.php
stubs/auth/app/Http/Livewire/Auth/Passwords/Confirm.php
stubs/auth/app/Http/Livewire/Auth/Passwords/Email.php
stubs/auth/app/Http/Livewire/Auth/Passwords/Reset.php
stubs/auth/app/Http/Livewire/Auth/Register.php
stubs/auth/app/Http/Livewire/Auth/Verify.php
stubs/auth/resources/views/layouts/auth.blade.php
stubs/auth/routes/web.php
stubs/auth/tests/Feature/Auth/LoginTest.php
stubs/auth/tests/Feature/Auth/LogoutTest.php
stubs/auth/tests/Feature/Auth/Passwords/ConfirmTest.php
stubs/auth/tests/Feature/Auth/Passwords/EmailTest.php
stubs/auth/tests/Feature/Auth/Passwords/ResetTest.php
stubs/auth/tests/Feature/Auth/RegisterTest.php
stubs/auth/tests/Feature/Auth/VerifyTest.php
stubs/default/resources/views/layouts/base.blade.php

This PR closes #63 and closes #60 by adding support for Livewire v2. Here is a list of changes made:
* Remove `Route::livewire()` methods in favour of `Route::get()` methods.
* Remove usage of `Route::layout()` methods in favour of `view()->extends()` inside of each Livewire component.
* Add an `isset` check for the `$slot` variable inside of `layouts.auth` so that regular `@section('content')` can be used, but it will also support Livewire's default usage of `{{ $slot }}`.
* Add a note to the README about Jetstream and point to it if you're looking for more than just authentication scaffolding. 
* Update the version of Alpine that is added to the `package.json` file from `^2.0` to `^2.6` since this version has all of the latest changes required for Livewire v2 to work correctly.
* Move …

chore(add support for Livewire v2)

---

composer.json

Laravel 8 require Laravel UI 3.0 or greater: https://laravel.com/docs/8.x/upgrade
Without this installation fails:
```
Problem 1
- Can only install one of: laravel/ui[3.x-dev, 2.x-dev].
- Can only install one of: laravel/ui[v3.0.0, 2.x-dev].
- laravel-frontend-presets/tall v2.0.0 requires laravel/ui ^2.0 -> satisfiable by laravel/ui[2.x-dev].
- Installation request for laravel-frontend-presets/tall ^2.0 -> satisfiable by laravel-frontend-presets/tall[v2.0.0].
- Installation request for laravel/ui ^3.0 -> satisfiable by laravel/ui[3.x-dev, v3.0.0].
```

Laravel 8 requires `laravel/ui:^3.0`

---

stubs/auth/app/Http/Livewire/Auth/Passwords/Reset.php
stubs/auth/tests/Feature/Auth/Passwords/ResetTest.php

In the password reset form it would be nice to prefill the email field with the query parameter.

Prefill email address in password reset form

---

stubs/default/resources/js/app.js
stubs/default/resources/js/bootstrap.js

Hey everyone,
Due to the issue I had regarding adding Alpine js plugins to the project such as Alpine-clipboard which have to be added before the Alpine js itself, struggled for hours and even people from the community were not able to answer the question, found out the Alpine js is declared in the ```bootstrap.js``` instead of ```app.js``` which is the proper place to declare a js package and/or alpine plugins. Therefore with the suggestion of @danharrin I'm opening this pull request to make sure other developers don't face the problem I did since ```bootstrap.js``` is not the right place to declare Alpine js and I don't think people will look into that file looking for Alpine js.

moving Alpine JS from Bootstrap.js to app.js

---

stubs/default/resources/views/layouts/base.blade.php

New install of L9 and the TALL framework and AlpineJS wouldn't work. Needed to wrap this in an array for it to load the app.js.

Needs to be in array

---

stubs/default/resources/js/app.js

Changed require() to import as used originally in the fresh install of Laravel.

Resolved "Uncaught ReferenceError: require is not defined"

---

src/TallPreset.php

- In version 0.5 they fixes autoprefixer warnings
- Fresh install tall-preset installs 0.4 version

Bump @tailwindcss/forms to a new version

---

stubs/default/resources/views/welcome.blade.php

Adding a space between Tailwind and CSS via @reinink 🤘

Adding a space inbetween Tailwind and CSS

---

src/TallPreset.php
stubs/default/resources/js/app.js

AlpineJS is already included in Livewire v3, so, no explicit installation and initialization is required anymore.

Removed AlpineJS initialization and its npm dependency
